#!/usr/bin/env bash

set -eo pipefail

echo "DATA_BASE_DIR=${DATA_BASE_DIR}" >> $GITHUB_ENV
echo "DATA_STAGING_SUBDIR=${DATA_STAGING_SUBDIR}" >> $GITHUB_ENV
echo "DATA_SOURCE_SUBDIR=${DATA_SOURCE_SUBDIR}" >> $GITHUB_ENV
echo "DATA_STAGING_DIR=${DATA_BASE_DIR}/${DATA_STAGING_SUBDIR}" >> $GITHUB_ENV
echo "DATA_SOURCE_DIR=${DATA_BASE_DIR}/${DATA_SOURCE_SUBDIR}" >> $GITHUB_ENV
echo "DATA_STORE_DIR=${DATA_BASE_DIR}/${DATA_SOURCE_SUBDIR}/data_store" >> $GITHUB_ENV