name: Parse feed

on:
  workflow_dispatch:
    inputs:
      feed:
        description: 'Feed URL'
        required: true

jobs:

  parse-feed:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse feed
        run: |
          python -m pip install -U pip
          python -m pip intall -r requirements.txt
          python parse-feed.py -f ${{ github.event.inputs.feed }}

