name: Refresh Feeds

on: workflow_dispatch

jobs:
  refresh-feeds:
    runs-on: ubuntu-latest
    container: mattwiley/ubuntu:20.04
    steps:

      - name: Checkout Logic
        uses: actions/checkout@v3

      - name: Setup Environment Variables
        shell: bash
        env:
          DATA_BASE_DIR: "${{ github.workspace }}/data"
          DATA_SOURCE_SUBDIR: "data_source"
          DATA_STAGING_SUBDIR: "data_staging"
        run: ./.github/workflows/tasks/setup_environment_variables.sh

      - name: Checkout Data
        shell: bash
        env:
          TOKEN: ${{ secrets.DATA_REPO_TOKEN }}
          CLONE_TARGET_DIR: ${{ env.DATA_SOURCE_DIR }}
        run: ./.github/workflows/tasks/checkout_data_repo.sh

      - name: Setup Python
        shell: bash
        run: ./.github/workflows/tasks/setup_python.sh
          
      - name: Install Python Dependencies
        shell: bash
        run: |
          set -eo pipefail
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Setup Config File for Add Source
        shell: bash
        env:
          BASE_DIR: ${{ env.DATA_BASE_DIR }}
          STORE_DIR: "${{ env.DATA_SOURCE_SUBDIR }}/data_store"
          STAGING_DIR: ${{ env.DATA_STAGING_SUBDIR }}
        run: python ./.github/workflows/tasks/setup_config.py

      - name: Refresh Feeds
        shell: bash
        run: |
          set -eo pipefail
          python parse-feeds.py
          cd ${{ env.DATA_STAGING_DIR }}
          ls -la
          pwd

      - name: Post Refresh
        shell: bash
        run: |
          set -eo pipefail
          ./post-staging.sh ${{ env.DATA_STAGING_DIR }} ${{ env.DATA_STORE_DIR }}
          cd ${{ env.DATA_STORE_DIR }}
          ls -la
          pwd

      - name: Blap
        shell: bash
        env:
          SOURCE_DIR: ${{ env.DATA_SOURCE_DIR }}
          UPDATED_FROM: ${{ github.actor == 'nektos/act' && 'nektos/act' || format('{0} {1}',github.workflow,github.run_number) }}
        run: ./.github/workflows/tasks/push_changes.sh
